--
-- Scripts for testing at the end of Sprint 3.5
-- These queries was generated by Claude.ai and reviewed by Sam Rodgers
--


-- Tests this trigger in f_conversion
--     expects 't' in column 'match'
--
-- CREATE TRIGGER trg_apply_conversion AFTER INSERT OR UPDATE ON analytics.f_conversion FOR EACH ROW EXECUTE FUNCTION analytics.apply_conversion();
--

SELECT 
    fc.tx_id,
    fc.base_amount,
    fc.fee_amount,
    f.rate,
    ROUND((fc.base_amount * f.rate) - fc.fee_amount, 4) AS expected_amount,
    ft.amount                                            AS actual_amount,
    ROUND((fc.base_amount * f.rate) - fc.fee_amount, 4) 
        = ROUND(ft.amount, 4)                            AS match
FROM analytics.f_conversion fc
JOIN analytics.f_fx_rate f   ON f.fx_id = fc.fx_id
JOIN analytics.f_transaction ft ON ft.tx_id = fc.tx_id
LIMIT 10;



-- Checks for any mismatches in the database
--     expects 0

SELECT COUNT(*) AS mismatches
FROM analytics.f_conversion fc
JOIN analytics.f_fx_rate f    ON f.fx_id = fc.fx_id
JOIN analytics.f_transaction ft ON ft.tx_id = fc.tx_id
WHERE ROUND((fc.base_amount * f.rate) - fc.fee_amount, 4) 
    != ROUND(ft.amount, 4);
    
    
    
-- Tests this trigger in f_conversion
-- Inserts a EUR conversion for a transaction that has no conversion row yet. The trigger should reject it if that transaction's currency doesn't match EUR.
--
-- CREATE TRIGGER trg_validate_conversion_currency BEFORE INSERT OR UPDATE ON analytics.f_conversion FOR EACH ROW EXECUTE FUNCTION analytics.validate_conversion_currency();
--

INSERT INTO analytics.f_conversion (base_amount, fee_amount, fx_id, tx_id)
SELECT 
    100.00,
    0.00,
    (SELECT fx_id FROM analytics.f_fx_rate WHERE base_cncy = 'EUR' LIMIT 1),
    (SELECT tx_id FROM analytics.f_transaction 
     WHERE tx_id NOT IN (SELECT tx_id FROM analytics.f_conversion)
     LIMIT 1);