-- This file contains the queries I will use for performance testing

--
-- SQL was generated by Claude AI and reviewed by Sam Rodgers
-- The implications and use cases of each query were considered by
--    Sam Rodgers and translated from plaintext description to code
--    by Claude AI.
-- Each query was carefully reviewed to confirm the expected functionality,
--    and it was determined no edits were needed.
--


-- Q1: Total transaction volume by company
-- Simple star join: f_transaction → d_company
-- Aggregates post-conversion USD amount per company.
-- Baseline query — no window functions, single join, high selectivity on c_id FK.
-- Expected to be fast at all scales; establishes the performance floor.

SELECT
    dc.c_name,
    dc.industry,
    dc.hq_country,
    COUNT(ft.tx_id)                  AS tx_count,
    ROUND(SUM(ft.amount), 2)         AS total_volume_usd,
    ROUND(AVG(ft.amount), 2)         AS avg_tx_usd
FROM analytics.f_transaction ft
JOIN analytics.d_company dc
    ON ft.c_id = dc.c_id
GROUP BY
    dc.c_id,
    dc.c_name,
    dc.industry,
    dc.hq_country
ORDER BY
    total_volume_usd DESC;