# config.py
# Canonical reference data for synthetic ETL pipeline.
# Structure is designed for direct consumption by noise.py and pipeline.py.
# All lookup tables are dicts (O(1)) rather than lists — important at millions of rows.
# This file was generated by Claude AI and lightly reviewed by Sam Rodgers.
# The intention of this aspect of data generation is that it is somewhat of
#     a mystery to the developer who has to deal with normalizing potentially
#     unfamiliar data.

import uuid as _uuid

# ============================================================
# SHARED UUID HELPERS
# ============================================================

# Fixed namespaces — do not change after first run or all derived UUIDs will rotate.
_COMPANY_NS  = _uuid.UUID("a1b2c3d4-e5f6-7890-abcd-ef1234567890")
_INDUSTRY_NS = _uuid.UUID("b2c3d4e5-f6a7-8901-bcde-f12345678901")
_CATEGORY_NS = _uuid.UUID("c3d4e5f6-a7b8-9012-cdef-123456789012")

def _company_uuid(key: str) -> str:
    """Deterministic UUID from company short key. Stable across runs."""
    return str(_uuid.uuid5(_COMPANY_NS, key))

def _industry_uuid(name: str) -> str:
    """Deterministic UUID from industry name. Stable across runs."""
    return str(_uuid.uuid5(_INDUSTRY_NS, name))

def _category_uuid(name: str) -> str:
    """Deterministic UUID from category name. Stable across runs."""
    return str(_uuid.uuid5(_CATEGORY_NS, name))


# ============================================================
# INDUSTRIES
# ============================================================
# Master industry registry.
# industry_id is a deterministic uuid5 — stable across runs and environments.
# display_cncy is the currency used in cross-company comparison views (BR-007, BR-008).
#
# Business rule (BR-013): a company's default_cncy must match its industry's
# display_cncy UNLESS display_cncy is USD (USD is always permitted).
#
# Insertion order: d_industry must be seeded before d_company (FK constraint).
# transform.py reads from this dict via seed_industries().

INDUSTRIES = {
    # key          : { industry_id, display_cncy }
    "Technology": {
        "industry_id":  _industry_uuid("Technology"),
        "display_cncy": "USD",
    },
    "Retail": {
        # EUR is the display currency for the EU retail segment.
        # Note: Nordic Trade AB (SEK) is permitted under BR-013 because
        # display_cncy is not USD — SEK does not match EUR, so if that
        # rule is ever strictly enforced this entry will need revisiting.
        # For now the pipeline treats the rule as a warning, not a hard error.
        "industry_id":  _industry_uuid("Retail"),
        "display_cncy": "EUR",
    },
    "Fintech": {
        "industry_id":  _industry_uuid("Fintech"),
        "display_cncy": "USD",
    },
    "Logistics": {
        "industry_id":  _industry_uuid("Logistics"),
        "display_cncy": "USD",
    },
}

# Reverse lookup: industry name → industry_id UUID string
# Used when building COMPANIES entries and by seed_companies() in transform.py.
INDUSTRY_NAME_TO_ID = {name: meta["industry_id"] for name, meta in INDUSTRIES.items()}


# ============================================================
# EXPENSE CATEGORIES
# ============================================================
# Master expense category registry.
# category_id is a deterministic uuid5 — stable across runs.
# transform.py seeds analytics.d_expense_category from this dict via
# seed_expense_categories(). Must be seeded before f_expense or
# raw.expense_event rows can be generated (FK constraint on category_id).

EXPENSE_CATEGORIES = {
    # category_name : category_id
    "Payroll":   _category_uuid("Payroll"),
    "Materials": _category_uuid("Materials"),
    "Utilities": _category_uuid("Utilities"),
    "Rent":      _category_uuid("Rent"),
    "Travel":    _category_uuid("Travel"),
    "Software":  _category_uuid("Software"),
}


# ============================================================
# COMPANIES
# ============================================================

# Master company registry — canonical short key is for human readability only.
# c_uuid is the actual DB identifier — deterministic uuid5 derived from the key.
# Same key always produces the same UUID across all runs and environments.
# Use this same namespace + key when seeding analytics.d_company.
#
# industry_id replaces the old plain "industry" string — it is a UUID FK to
# analytics.d_industry. Always resolved via INDUSTRY_NAME_TO_ID so there is
# one place to change if an industry is renamed.
#
# noise.py will inject: nulls, names instead of IDs, casing variants, whitespace.
# normalize_receipts() must trim + upper + map through COMPANY_NAME_TO_UUID.
#
# Runtime additions: call register_company() to add a company without restarting
# the process. The flat caches (COMPANY_KEYS, COMPANY_WEIGHTS, etc.) are rebuilt
# automatically. See register_company() below.

COMPANIES = {
    # key   : { c_uuid, name, industry_id, hq_country, region, default_cncy, weight }
    # c_uuid      = DB identifier written to raw.transaction_event.c_id and analytics.d_company.c_id
    # industry_id = FK to analytics.d_industry — must exist before d_company is seeded
    # hq_country  = required NOT NULL in analytics.d_company
    "COMP001": {"c_uuid": _company_uuid("COMP001"), "name": "Orion Systems",        "industry_id": INDUSTRY_NAME_TO_ID["Technology"], "hq_country": "United States", "region": "US_TECH",        "default_cncy": "USD", "weight": 0.18},
    "COMP002": {"c_uuid": _company_uuid("COMP002"), "name": "BluePeak Analytics",   "industry_id": INDUSTRY_NAME_TO_ID["Technology"], "hq_country": "United States", "region": "US_TECH",        "default_cncy": "USD", "weight": 0.12},
    "COMP003": {"c_uuid": _company_uuid("COMP003"), "name": "NexaData Corp",        "industry_id": INDUSTRY_NAME_TO_ID["Technology"], "hq_country": "United States", "region": "US_TECH",        "default_cncy": "USD", "weight": 0.10},
    "COMP004": {"c_uuid": _company_uuid("COMP004"), "name": "AlpenMart GmbH",       "industry_id": INDUSTRY_NAME_TO_ID["Retail"],     "hq_country": "Germany",       "region": "EU_RETAIL",      "default_cncy": "EUR", "weight": 0.09},
    "COMP005": {"c_uuid": _company_uuid("COMP005"), "name": "Nordic Trade AB",      "industry_id": INDUSTRY_NAME_TO_ID["Retail"],     "hq_country": "Sweden",        "region": "EU_RETAIL",      "default_cncy": "SEK", "weight": 0.08},
    "COMP006": {"c_uuid": _company_uuid("COMP006"), "name": "Louvre Commerce SARL", "industry_id": INDUSTRY_NAME_TO_ID["Retail"],     "hq_country": "France",        "region": "EU_RETAIL",      "default_cncy": "EUR", "weight": 0.07},
    "COMP007": {"c_uuid": _company_uuid("COMP007"), "name": "ZenPay Ltd",           "industry_id": INDUSTRY_NAME_TO_ID["Fintech"],    "hq_country": "Singapore",     "region": "APAC_FINTECH",   "default_cncy": "SGD", "weight": 0.10},
    "COMP008": {"c_uuid": _company_uuid("COMP008"), "name": "Kumo Holdings",        "industry_id": INDUSTRY_NAME_TO_ID["Fintech"],    "hq_country": "Japan",         "region": "APAC_FINTECH",   "default_cncy": "JPY", "weight": 0.08},
    "COMP009": {"c_uuid": _company_uuid("COMP009"), "name": "Pacific Ledger Co",    "industry_id": INDUSTRY_NAME_TO_ID["Fintech"],    "hq_country": "Hong Kong",     "region": "APAC_FINTECH",   "default_cncy": "HKD", "weight": 0.06},
    "COMP010": {"c_uuid": _company_uuid("COMP010"), "name": "Andes Logistics",      "industry_id": INDUSTRY_NAME_TO_ID["Logistics"],  "hq_country": "Mexico",        "region": "LATAM_SERVICES", "default_cncy": "MXN", "weight": 0.05},
    "COMP011": {"c_uuid": _company_uuid("COMP011"), "name": "RioSoft Tecnologia",   "industry_id": INDUSTRY_NAME_TO_ID["Technology"], "hq_country": "Brazil",        "region": "LATAM_SERVICES", "default_cncy": "BRL", "weight": 0.04},
    "COMP012": {"c_uuid": _company_uuid("COMP012"), "name": "Patagonia Digital",    "industry_id": INDUSTRY_NAME_TO_ID["Logistics"],  "hq_country": "Argentina",     "region": "LATAM_SERVICES", "default_cncy": "USD", "weight": 0.03},
}

# ── Flat caches derived from COMPANIES ───────────────────────────────────────
# These are the structures consumed by transactions.py and noise.py.
# They are rebuilt by _rebuild_company_caches() whenever a company is added
# at runtime via register_company(). Do not modify them directly.

def _rebuild_company_caches():
    """
    Recompute all flat COMPANIES-derived caches in place.
    Called once at module load and again after every register_company() call.
    Mutates module-level names so all importers see the updated state without
    needing to re-import.
    """
    global COMPANY_KEYS, COMPANY_WEIGHTS, COMPANY_IDS, COMPANY_NAME_TO_UUID

    COMPANY_KEYS = list(COMPANIES.keys())

    # Weights must be normalised so they sum to 1.0 for np.random.choice.
    raw_weights = [COMPANIES[k]["weight"] for k in COMPANY_KEYS]
    total = sum(raw_weights)
    COMPANY_WEIGHTS = [w / total for w in raw_weights]

    COMPANY_IDS = [COMPANIES[k]["c_uuid"] for k in COMPANY_KEYS]

    # Reverse lookup: normalised name → c_uuid
    # Used by normalize_receipts() to recover c_id from injected name noise.
    COMPANY_NAME_TO_UUID = {v["name"].upper(): v["c_uuid"] for v in COMPANIES.values()}
    COMPANY_NAME_TO_UUID.update({
        "ORION SYSTEMS INC":  COMPANIES["COMP001"]["c_uuid"],
        "BLUEPEAK":           COMPANIES["COMP002"]["c_uuid"],
        "NEXADATA":           COMPANIES["COMP003"]["c_uuid"],
        "ALPENMART":          COMPANIES["COMP004"]["c_uuid"],
        "ZENPAY":             COMPANIES["COMP007"]["c_uuid"],
    })


# Initialise caches at import time.
COMPANY_KEYS: list[str]
COMPANY_WEIGHTS: list[float]
COMPANY_IDS: list[str]
COMPANY_NAME_TO_UUID: dict[str, str]
_rebuild_company_caches()


# ── Runtime company registration ──────────────────────────────────────────────

def register_company(
    key: str,
    name: str,
    industry_name: str,
    hq_country: str,
    region: str,
    default_cncy: str,
    weight: float = 0.05,
    c_uuid: str | None = None,
) -> dict:
    """
    Add a new company to the live registry at runtime.

    Intended for the dashboard's "ingest new company" flow — a company added
    here will immediately be visible to generate_transactions() and
    seed_companies() without restarting the process.

    The company is also written to analytics.d_company by the next
    run_seed() / seed_companies() call in transform.py. Callers that need
    the row in the DB immediately should call seed_companies() on an open
    connection after this.

    Args:
        key:           Short key, e.g. "COMP013". Must be unique in COMPANIES.
        name:          Human-readable company name.
        industry_name: Must be a key in INDUSTRIES (e.g. "Technology").
        hq_country:    Country string, e.g. "United States".
        region:        Region tag, e.g. "US_TECH".
        default_cncy:  ISO currency code for this company's default currency.
        weight:        Sampling weight for transaction generation. Will be
                       normalised against the full set automatically.
        c_uuid:        Optional explicit UUID. If omitted, derived from key
                       using the standard deterministic namespace — meaning the
                       same key always produces the same UUID.

    Returns:
        The newly created company dict (same shape as COMPANIES entries).

    Raises:
        ValueError: if key already exists, industry_name is unknown, or
                    default_cncy is not a recognised currency code.
    """
    if key in COMPANIES:
        raise ValueError(f"Company key {key!r} already exists in COMPANIES.")

    if industry_name not in INDUSTRIES:
        raise ValueError(
            f"Unknown industry {industry_name!r}. "
            f"Known industries: {list(INDUSTRIES.keys())}"
        )

    if default_cncy not in CURRENCY_CODES:
        raise ValueError(
            f"Unknown currency {default_cncy!r}. "
            f"Known codes: {sorted(CURRENCY_CODES)}"
        )

    entry = {
        "c_uuid":       c_uuid if c_uuid is not None else _company_uuid(key),
        "name":         name,
        "industry_id":  INDUSTRY_NAME_TO_ID[industry_name],
        "hq_country":   hq_country,
        "region":       region,
        "default_cncy": default_cncy,
        "weight":       weight,
    }

    COMPANIES[key] = entry
    _rebuild_company_caches()
    return entry


# ============================================================
# CURRENCIES
# ============================================================

# Master currency registry.
# noise.py will inject: lowercase, aliases, symbols, flipped base/quote, missing fields.
# normalize_receipts() must resolve through CURRENCY_ALIAS_MAP then validate against this set.

CURRENCIES = {
    "USD": {"name": "US Dollar",           "fx_start_rate": 1.0,    "region": "US"},
    "EUR": {"name": "Euro",                "fx_start_rate": 0.92,   "region": "EU"},
    "GBP": {"name": "British Pound",       "fx_start_rate": 0.79,   "region": "EU"},
    "JPY": {"name": "Japanese Yen",        "fx_start_rate": 149.5,  "region": "APAC"},
    "AUD": {"name": "Australian Dollar",   "fx_start_rate": 1.53,   "region": "APAC"},
    "CAD": {"name": "Canadian Dollar",     "fx_start_rate": 1.36,   "region": "US"},
    "CHF": {"name": "Swiss Franc",         "fx_start_rate": 0.89,   "region": "EU"},
    "SEK": {"name": "Swedish Krona",       "fx_start_rate": 10.4,   "region": "EU"},
    "NOK": {"name": "Norwegian Krone",     "fx_start_rate": 10.6,   "region": "EU"},
    "MXN": {"name": "Mexican Peso",        "fx_start_rate": 19.5,   "region": "LATAM"},
    "BRL": {"name": "Brazilian Real",      "fx_start_rate": 5.70,   "region": "LATAM"},
    "SGD": {"name": "Singapore Dollar",    "fx_start_rate": 1.34,   "region": "APAC"},
    "HKD": {"name": "Hong Kong Dollar",    "fx_start_rate": 7.82,   "region": "APAC"},
    "AED": {"name": "UAE Dirham",          "fx_start_rate": 3.67,   "region": "ME"},
}

# Flat set for O(1) membership checks in validation
CURRENCY_CODES = set(CURRENCIES.keys())

# Alias map — every dirty variant resolves to a canonical ISO code.
# noise.py draws from the keys; normalize_receipts() resolves them.
CURRENCY_ALIAS_MAP = {
    # USD variants
    "usd":         "USD",
    "us dollars":  "USD",
    "us dollar":   "USD",
    "$":           "USD",
    "u.s.d.":      "USD",
    "dollar":      "USD",
    # EUR variants
    "eur":         "EUR",
    "euro":        "EUR",
    "euros":       "EUR",
    "€":           "EUR",
    # GBP variants
    "gbp":         "GBP",
    "pound":       "GBP",
    "pounds":      "GBP",
    "£":           "GBP",
    "sterling":    "GBP",
    # JPY variants
    "jpy":         "JPY",
    "yen":         "JPY",
    "¥":           "JPY",
    # AUD variants
    "aud":         "AUD",
    "a$":          "AUD",
    "australian":  "AUD",
    # CAD variants
    "cad":         "CAD",
    "c$":          "CAD",
    "canadian":    "CAD",
    # CHF variants
    "chf":         "CHF",
    "franc":       "CHF",
    "francs":      "CHF",
    # SEK variants
    "sek":         "SEK",
    "krona":       "SEK",
    # NOK variants
    "nok":         "NOK",
    "krone":       "NOK",
    # MXN variants
    "mxn":         "MXN",
    "peso":        "MXN",
    # BRL variants
    "brl":         "BRL",
    "real":        "BRL",
    "reais":       "BRL",
    "r$":          "BRL",
    # SGD variants
    "sgd":         "SGD",
    "s$":          "SGD",
    # HKD variants
    "hkd":         "HKD",
    "hk$":         "HKD",
    # AED variants
    "aed":         "AED",
    "dirham":      "AED",
    "dirhams":     "AED",
}


# ============================================================
# PRODUCTS
# ============================================================

# Used for generating realistic base_amount distributions per product type.
# noise.py will inject: fee inside base_amount, percent-string fees, missing fees.

PRODUCTS = {
    "SAAS_BASIC":         {"mean_price": 50,   "volatility": 10,  "fee_rate": 0.005},
    "SAAS_PRO":           {"mean_price": 200,  "volatility": 40,  "fee_rate": 0.005},
    "ENTERPRISE_LICENSE": {"mean_price": 5000, "volatility": 500, "fee_rate": 0.003},
    "API_USAGE":          {"mean_price": 0.05, "volatility": 0.02,"fee_rate": 0.010},
    "CONSULTING_HOUR":    {"mean_price": 150,  "volatility": 30,  "fee_rate": 0.008},
}

PRODUCT_CODES = list(PRODUCTS.keys())


# ============================================================
# TIMESTAMP NOISE FORMATS
# ============================================================
# noise.py draws from TIMESTAMP_NOISE_FORMATS to replace clean ISO timestamps.
# normalize_receipts() must attempt each parser in TIMESTAMP_PARSE_ORDER.
# Clean format: "{iso}" "2026-02-14 13:45:00"

TIMESTAMP_NOISE_FORMATS = [
    "{mm}/{dd}/{yyyy} {h}:{mm_t} {ampm}",  # "02/14/2026 1:45 PM"
    "{dd}-{mm}-{yyyy} {HH}:{MM}",          # "14-02-2026 13:45"
    "{excel_serial}",                       # "44589.572"  (Excel float)
    None,                                   # null (small %)
]

# Weights for how often each format is injected (must sum to 1.0)
# Order matches TIMESTAMP_NOISE_FORMATS
TIMESTAMP_NOISE_WEIGHTS = [0.35, 0.30, 0.25, 0.10]

# Ordered list of strptime format strings for multi-format parsing fallback
TIMESTAMP_PARSE_ORDER = [
    "%Y-%m-%d %H:%M:%S",
    "%Y-%m-%dT%H:%M:%S",
    "%Y-%m-%dT%H:%M:%SZ",
    "%m/%d/%Y %I:%M %p",
    "%m/%d/%Y %H:%M",
    "%d-%m-%Y %H:%M",
    "%d/%m/%Y %H:%M:%S",
    "%Y/%m/%d %H:%M:%S",
]


# ============================================================
# AMOUNT NOISE FORMATS
# ============================================================
# noise.py uses these templates to format clean float amounts as dirty strings.
# normalize_receipts() must strip and parse back to float.
# Clean version:     "standard",         # 1200.50

AMOUNT_NOISE_FORMATS = [
    "comma_thousands",  # 1,200.50
    "eu_decimal",       # 1.200,50  (European locale)
    "space_thousands",  # 1 200.50
    "negative",         # -1200.50  (refund)
    "parentheses",      # (1200.50) (accounting negative)
    "with_symbol",      # $1200.50
]

AMOUNT_NOISE_WEIGHTS = [0.25, 0.25, 0.20, 0.20, 0.05, 0.05]


# ============================================================
# COLUMN NAME SCHEMAS (per company profile)
# ============================================================
# Each company sends data with different column names.
# noise.py selects a schema per company_id and renames columns accordingly.
# normalize_receipts() maps back to canonical schema using CANONICAL_COLUMN_MAP.
#
# New companies added via register_company() can supply their own column schema
# by calling register_company_column_schema() after registration. Until they do,
# the "_default" schema is used.

COMPANY_COLUMN_SCHEMAS = {
    "COMP001": {
        "tx_timestamp": "tx_time",
        "company_id":   "company",
        "base_cncy":    "currency",
        "amount":       "amount",
        "fee_amount":   "fee",
    },
    "COMP004": {
        "tx_timestamp": "timestamp",
        "company_id":   "firm_id",
        "base_cncy":    "base_cncy",
        "amount":       "base_amount",
        "fee_amount":   "service_fee",
    },
    "COMP007": {
        "tx_timestamp": "date",
        "company_id":   "seller",
        "base_cncy":    "curr",
        "amount":       "gross_value",
        "fee_amount":   "charges",
    },
    "COMP009": {
        "tx_timestamp": "transaction_date",
        "company_id":   "client_id",
        "base_cncy":    "payment_currency",
        "amount":       "transaction_amount",
        "fee_amount":   "processing_fee",
    },
    "COMP011": {
        "tx_timestamp": "data_hora",
        "company_id":   "empresa_id",
        "base_cncy":    "moeda",
        "amount":       "valor",
        "fee_amount":   "taxa",
    },
    # All other companies use canonical names by default
    "_default": {
        "tx_timestamp": "tx_timestamp",
        "company_id":   "company_id",
        "base_cncy":    "base_cncy",
        "amount":       "amount",
        "fee_amount":   "fee_amount",
    },
}


def register_company_column_schema(key: str, schema: dict) -> None:
    """
    Register a custom column name schema for a company.

    Called after register_company() when the new company's data feed uses
    non-canonical column names. Updates CANONICAL_COLUMN_MAP in place so
    normalize_receipts() can resolve the new names immediately.

    Args:
        key:    Company key, e.g. "COMP013". Does not need to exist in
                COMPANIES — schemas can be registered independently.
        schema: Dict mapping canonical name → dirty name, e.g.
                {"tx_timestamp": "date", "amount": "gross_value", ...}
                Must use the same canonical keys as the "_default" schema.
    """
    COMPANY_COLUMN_SCHEMAS[key] = schema
    # Rebuild the inverted map so new dirty names are immediately resolvable.
    _rebuild_canonical_column_map()


def _rebuild_canonical_column_map() -> None:
    """Rebuild CANONICAL_COLUMN_MAP from the current COMPANY_COLUMN_SCHEMAS."""
    global CANONICAL_COLUMN_MAP
    CANONICAL_COLUMN_MAP = {}
    for _schema in COMPANY_COLUMN_SCHEMAS.values():
        for canonical, dirty in _schema.items():
            CANONICAL_COLUMN_MAP[dirty] = canonical


# Inverted: all known dirty column names → canonical name
# Auto-built from COMPANY_COLUMN_SCHEMAS so there's one place to update.
# Also rebuilt by _rebuild_canonical_column_map() when new schemas are added.
CANONICAL_COLUMN_MAP: dict[str, str]
_rebuild_canonical_column_map()


# ============================================================
# NOISE INJECTION RATES
# ============================================================
# Top-level dials — adjust these to stress-test your pipeline harder or softer.
# noise.py reads these rather than hardcoding percentages inline.

NOISE_RATES = {
    "timestamp_format":  0.20,   # 20% of rows get a non-ISO timestamp
    "timestamp_null":    0.02,   # 2%  of rows get a null timestamp
    "currency_dirty":    0.10,   # 10% of rows get a currency alias/variant
    "amount_dirty":      0.15,   # 15% of rows get a formatted amount string
    "company_id_null":   0.01,   # 1%  of rows get null company_id (reduced to limit <NULL> quarantine dominance)
    "company_id_name":   0.04,   # 4%  of rows get company name instead of ID
    "fee_missing":       0.05,   # 5%  of rows have no fee
    "fee_as_percent":    0.03,   # 3%  of rows express fee as "2%"
    "fee_in_base":       0.02,   # 2%  of rows have fee bundled into base_amount
    "malformed_row":     0.05,   # 5%  of rows are structurally broken
    "missing_fields":    0.03,   # 3%  of rows have one or more fields dropped
    "source_dirty":      0.08,   # 8%  of rows get a dirty source variant
}


# ============================================================
# SOURCE VALUES
# ============================================================
# Clean source system names — used by transactions.py for generation.
# Weights control how often each source appears in clean data.
# noise.py injects dirty variants from SOURCE_NOISE_VARIANTS.

SOURCE_VALUES = {
    "api":           0.60,
    "manual_upload": 0.15,
    "batch_csv":     0.12,
    "sftp_feed":     0.08,
    "webhook":       0.05,
}

# Dirty variants noise.py can inject per canonical source value
SOURCE_NOISE_VARIANTS = {
    "api":           ["API", "Api", "api ", " api", None],
    "manual_upload": ["Manual Upload", "manual upload", "MANUAL_UPLOAD", "manual-upload"],
    "batch_csv":     ["Batch CSV", "batch_CSV", "batchcsv", "BATCH_CSV"],
    "sftp_feed":     ["SFTP", "sftp feed", "sftp-feed", "SFTPFeed"],
    "webhook":       ["Webhook", "WEBHOOK", "web_hook", "Web Hook"],
}