# fx_source.py
# Unified interface for FX rate generation.
#
# The dashboard has a toggle that switches the pipeline between two FX sources:
#   "live"      — rates fetched from the frankfurter.app API via live_fx.py
#   "synthetic" — rates generated by a GBM model via synthetic_fx.py
#
# This module is the single place that knows about both sources. Everything
# else (main.py, the dashboard API, tests) calls get_fx_rates() and never
# imports live_fx or synthetic_fx directly.
#
# Active source is stored in _active_source — a module-level string that the
# dashboard writes to via set_source(). The default is "synthetic" so the
# pipeline works out of the box without a live API connection.
#
# Live mode vs synthetic mode — what each provides:
#
#   synthetic:
#     Returns a pd.DataFrame with columns (fx_timestamp, base_cncy,
#     quote_cncy, rate) covering a specified time window at 5s granularity.
#     Suitable for batch runs via main.py where a time window is known upfront.
#
#   live:
#     Returns the most recent rates fetched by the background live_fx.py
#     process by reading directly from raw.fx_rate. This means live_fx.py
#     must already be running and inserting rows. get_fx_rates() in live mode
#     queries the DB for the latest tick per currency pair and returns a
#     single-row-per-pair DataFrame in the same shape as synthetic output.
#     The caller (main.py) can then pass this to load_fx_rates() as normal —
#     the ON CONFLICT guard means re-inserting already-present rows is safe.
#
# Switching at runtime:
#   from fx_source import set_source, get_source
#   set_source("live")       # dashboard toggle ON
#   set_source("synthetic")  # dashboard toggle OFF

import logging
from datetime import datetime, timezone

import pandas as pd

logger = logging.getLogger(__name__)

# ── Active source state ───────────────────────────────────────────────────────

_VALID_SOURCES = {"live", "synthetic"}
_active_source: str = "synthetic"


def get_source() -> str:
    """Return the currently active FX source ("live" or "synthetic")."""
    return _active_source


def set_source(source: str) -> None:
    """
    Switch the active FX source.

    Args:
        source: "live" or "synthetic"

    Raises:
        ValueError if source is not a recognised value.
    """
    global _active_source
    if source not in _VALID_SOURCES:
        raise ValueError(
            f"Unknown FX source {source!r}. "
            f"Valid options: {sorted(_VALID_SOURCES)}"
        )
    if source != _active_source:
        logger.info(f"FX source switched: {_active_source!r} → {source!r}")
        _active_source = source


# ── Unified fetch ─────────────────────────────────────────────────────────────

def get_fx_rates(
    start_ts: datetime | None = None,
    end_ts:   datetime | None = None,
    conn=None,
) -> pd.DataFrame:
    """
    Return a DataFrame of FX rates using the currently active source.

    The returned DataFrame always has these columns regardless of source:
        fx_timestamp  — timestamptz
        base_cncy     — varchar(3)
        quote_cncy    — varchar(3), always "USD"
        rate          — numeric(14,7)

    Args:
        start_ts: Start of the time window (required for synthetic mode).
        end_ts:   End of the time window (required for synthetic mode).
        conn:     psycopg2 connection (required for live mode — used to
                  query the latest rates from raw.fx_rate).

    Returns:
        pd.DataFrame in the shape expected by loader.load_fx_rates().

    Raises:
        ValueError if required arguments for the active source are missing.
    """
    if _active_source == "synthetic":
        return _get_synthetic(start_ts, end_ts)
    else:
        return _get_live(conn)


# ── Synthetic source ──────────────────────────────────────────────────────────

def _get_synthetic(
    start_ts: datetime | None,
    end_ts:   datetime | None,
) -> pd.DataFrame:
    """
    Generate a synthetic FX rate DataFrame for the given time window.

    Delegates entirely to synthetic_fx.generate_all_fx_series — this
    function exists only to enforce argument validation and keep the
    dispatch logic in one place.
    """
    if start_ts is None or end_ts is None:
        raise ValueError(
            "start_ts and end_ts are required when FX source is 'synthetic'."
        )

    from config import CURRENCY_CODES
    from synthetic_fx import generate_all_fx_series

    logger.debug(
        f"FX source: synthetic | window {start_ts.isoformat()} "
        f"→ {end_ts.isoformat()}"
    )
    return generate_all_fx_series(start_ts, end_ts, CURRENCY_CODES)


# ── Live source ───────────────────────────────────────────────────────────────

# SQL that returns the single most recent rate per currency pair from
# raw.fx_rate. The DISTINCT ON / ORDER BY pattern is standard PostgreSQL
# for "latest row per group".
_SQL_LATEST_RATES = """
    SELECT DISTINCT ON (base_cncy, quote_cncy)
        fx_timestamp,
        base_cncy,
        quote_cncy,
        rate
    FROM raw.fx_rate
    ORDER BY base_cncy, quote_cncy, fx_timestamp DESC
"""


def _get_live(conn) -> pd.DataFrame:
    """
    Read the most recent rate per currency pair from raw.fx_rate.

    live_fx.py must be running and inserting rows for this to return
    current data. If the table is empty (e.g. live_fx.py has not started
    yet) an empty DataFrame is returned and a warning is logged — the
    caller should handle this gracefully rather than crashing.

    Args:
        conn: Active psycopg2 connection. Passed in by the caller so this
              module does not own connection lifecycle.

    Returns:
        pd.DataFrame with columns: fx_timestamp, base_cncy, quote_cncy, rate
    """
    if conn is None:
        raise ValueError(
            "A psycopg2 connection is required when FX source is 'live'. "
            "Pass conn= to get_fx_rates()."
        )

    with conn.cursor() as cur:
        cur.execute(_SQL_LATEST_RATES)
        rows = cur.fetchall()

    if not rows:
        logger.warning(
            "FX source: live — raw.fx_rate is empty. "
            "Is live_fx.py running? Returning empty DataFrame."
        )
        return pd.DataFrame(
            columns=["fx_timestamp", "base_cncy", "quote_cncy", "rate"]
        )

    df = pd.DataFrame(
        rows,
        columns=["fx_timestamp", "base_cncy", "quote_cncy", "rate"],
    )

    logger.debug(
        f"FX source: live | {len(df)} pairs, "
        f"latest tick: {df['fx_timestamp'].max()}"
    )
    return df
