-- Generated by Claude AI and reviewed for correctness by Sam Rodgers

-- Migration 001: Add d_industry and d_expense_category
-- Description: Adds two new dimension tables required for the schema rework.
--              d_industry supports industry-level aggregation and peer comparison.
--              d_expense_category supports categorization of company expense events.
-- Depends on:  analytics.d_currency (d_industry references it for display_cncy)
-- Safe to run: Yes — additive only, no existing tables altered.

BEGIN;

-- d_industry
-- Represents a business industry. Defines the display currency that member
-- companies inherit when shown in a comparison context. Industries spanning
-- multiple regions should use 'USD' as display_cncy per BR-008.

CREATE TABLE analytics.d_industry (
    industry_id  uuid         DEFAULT gen_random_uuid() NOT NULL,
    name         varchar(60)  NOT NULL,
    display_cncy varchar(3)   NOT NULL,

    CONSTRAINT d_industry_pkey
        PRIMARY KEY (industry_id),

    CONSTRAINT d_industry_display_cncy_fkey
        FOREIGN KEY (display_cncy)
        REFERENCES analytics.d_currency (cncy_code)
);

ALTER TABLE analytics.d_industry OWNER TO alex_analytics;

COMMENT ON TABLE  analytics.d_industry              IS 'Industry dimension. One row per industry.';
COMMENT ON COLUMN analytics.d_industry.display_cncy IS 'Display currency inherited by member companies in comparison views (BR-007, BR-008).';


-- d_expense_category
-- Defines valid expense categories (e.g. Payroll, Materials, Utilities).
-- Stored as data rather than a schema enum so categories can be added
-- without a migration (BR-021).

CREATE TABLE analytics.d_expense_category (
    category_id   uuid        DEFAULT gen_random_uuid() NOT NULL,
    category_name varchar(60) NOT NULL,

    CONSTRAINT d_expense_category_pkey
        PRIMARY KEY (category_id),

    CONSTRAINT d_expense_category_name_unique
        UNIQUE (category_name)
);

ALTER TABLE analytics.d_expense_category OWNER TO alex_analytics;

COMMENT ON TABLE analytics.d_expense_category IS 'Expense category dimension. One row per category. Managed as data to allow additions without schema migrations (BR-021).';

COMMIT;
