-- Generated by Claude AI and reviewed for correctness by Sam Rodgers

-- Migration 002: Alter d_company
-- Description: Replaces the denormalized industry varchar column with a proper
--              FK to d_industry (BR-012). Also fixes default_cncy from CHAR(3)
--              to VARCHAR(3) to prevent trailing space padding issues (BR-005).
-- Depends on:  001_add_dimension_tables.sql (d_industry must exist)
-- Safe to run: Yes — table is empty in current local instance.
-- WARNING:     If d_company contains rows, industry_id cannot be populated
--              automatically. You would need to insert rows into d_industry
--              first and then manually map existing company rows before
--              dropping the industry column.

BEGIN;

-- Step 1: Add industry_id column (nullable initially so the statement
-- succeeds even if the table has rows — set NOT NULL after populating)
ALTER TABLE analytics.d_company
    ADD COLUMN industry_id uuid;

-- Step 2: Add FK constraint to d_industry
ALTER TABLE analytics.d_company
    ADD CONSTRAINT d_company_industry_id_fkey
        FOREIGN KEY (industry_id)
        REFERENCES analytics.d_industry (industry_id);

-- Step 3: Add index to support join performance on industry_id
CREATE INDEX idx_d_company_industry_id
    ON analytics.d_company (industry_id);

-- Step 4: Enforce NOT NULL now that the column and FK are in place.
-- If this fails, rows exist without an industry_id — see WARNING above.
ALTER TABLE analytics.d_company
    ALTER COLUMN industry_id SET NOT NULL;

-- Step 5: Drop the old denormalized industry varchar column
ALTER TABLE analytics.d_company
    DROP COLUMN industry;

-- Step 6: Fix default_cncy from CHAR(3) to VARCHAR(3) (BR-005)
ALTER TABLE analytics.d_company
    ALTER COLUMN default_cncy TYPE varchar(3);

-- Step 7: Add FK from default_cncy to d_currency now that the type matches
ALTER TABLE analytics.d_company
    ADD CONSTRAINT d_company_default_cncy_fkey
        FOREIGN KEY (default_cncy)
        REFERENCES analytics.d_currency (cncy_code);

COMMENT ON COLUMN analytics.d_company.industry_id IS 'FK to d_industry. Defines the industry this company belongs to (BR-012). Display currency is inherited from d_industry.display_cncy (BR-007).';
COMMENT ON COLUMN analytics.d_company.default_cncy IS 'Default display currency for this company (BR-006). Must match d_industry.display_cncy unless industry display_cncy is USD (BR-013).';

COMMIT;
