-- Generated by Claude AI and reviewed for correctness by Sam Rodgers

-- Migration 003: Convert CHAR(3) currency columns to VARCHAR(3)
-- Description: Fixes trailing space padding issue across all currency code
--              columns in both schemas (BR-005). Also updates the
--              validate_conversion_currency function's local variable
--              declarations for consistency.
-- Depends on:  001, 002
-- Safe to run: Yes — type change from CHAR(3) to VARCHAR(3) is compatible
--              in PostgreSQL. Existing data is preserved and constraints
--              remain in place.

BEGIN;

-- analytics.d_currency
-- cncy_code is the PK and the target of all currency FKs. PostgreSQL allows
-- this type change without dropping dependent constraints as long as the
-- new type is binary-compatible, which VARCHAR(3) is with CHAR(3).
ALTER TABLE analytics.d_currency
    ALTER COLUMN cncy_code TYPE varchar(3);

-- Remove the default 'XXX' cast which references the old character varying
-- literal — reapply it cleanly as varchar
ALTER TABLE analytics.d_currency
    ALTER COLUMN cncy_code SET DEFAULT 'XXX';

-- analytics.f_fx_rate
ALTER TABLE analytics.f_fx_rate
    ALTER COLUMN base_cncy TYPE varchar(3);

ALTER TABLE analytics.f_fx_rate
    ALTER COLUMN quote_cncy TYPE varchar(3);

-- analytics.f_transaction
-- cncy was already VARCHAR(3) in the original schema but listed as
-- character varying(3) — explicitly restate for consistency
ALTER TABLE analytics.f_transaction
    ALTER COLUMN cncy TYPE varchar(3);

-- raw.transaction_event
ALTER TABLE raw.transaction_event
    ALTER COLUMN quote_cncy TYPE varchar(3);

-- Update validate_conversion_currency function to use varchar(3)
-- for its local variable declarations for consistency (BR-005)
CREATE OR REPLACE FUNCTION analytics.validate_conversion_currency()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_tx_cncy   varchar(3);
    v_base_cncy varchar(3);
BEGIN
    SELECT cncy INTO v_tx_cncy
    FROM analytics.f_transaction
    WHERE tx_id = NEW.tx_id;

    SELECT base_cncy INTO v_base_cncy
    FROM analytics.f_fx_rate
    WHERE fx_id = NEW.fx_id;

    IF v_tx_cncy IS DISTINCT FROM v_base_cncy THEN
        RAISE EXCEPTION
            'Transaction currency (%) does not match FX base currency (%)',
            v_tx_cncy, v_base_cncy;
    END IF;

    RETURN NEW;
END;
$$;

ALTER FUNCTION analytics.validate_conversion_currency() OWNER TO alex_analytics;

COMMIT;
