-- Generated by Claude AI and reviewed for correctness by Sam Rodgers

-- Migration 004: Add f_expense
-- Description: Adds the expense fact table to the analytics schema.
--              Records one expense event per company per point in time.
--              USD only for current version — multi-currency support
--              deferred alongside f_transaction (BR-022).
-- Depends on:  001 (d_expense_category)
--              002 (d_company)
--              003 (varchar currency codes)
--              analytics.d_time, analytics.d_currency must exist

BEGIN;

CREATE TABLE analytics.f_expense (
    expense_id  uuid            DEFAULT gen_random_uuid() NOT NULL,
    amount      numeric(18,4)   NOT NULL,
    cncy        varchar(3)      NOT NULL,
    c_id        uuid            NOT NULL,
    time_id     uuid            NOT NULL,
    category_id uuid            NOT NULL,

    CONSTRAINT f_expense_pkey
        PRIMARY KEY (expense_id),

    CONSTRAINT f_expense_c_id_fkey
        FOREIGN KEY (c_id)
        REFERENCES analytics.d_company (c_id),

    CONSTRAINT f_expense_time_id_fkey
        FOREIGN KEY (time_id)
        REFERENCES analytics.d_time (time_id),

    CONSTRAINT f_expense_category_id_fkey
        FOREIGN KEY (category_id)
        REFERENCES analytics.d_expense_category (category_id),

    CONSTRAINT f_expense_cncy_fkey
        FOREIGN KEY (cncy)
        REFERENCES analytics.d_currency (cncy_code)
);

COMMENT ON TABLE  analytics.f_expense             IS 'Expense fact table. Grain: one expense event for one company at one point in time (BR-019). USD only until multi-currency support is implemented (BR-022).';
COMMENT ON COLUMN analytics.f_expense.amount      IS 'Expense amount in the recorded currency. Currently expected to be USD (BR-022).';
COMMENT ON COLUMN analytics.f_expense.cncy        IS 'Currency of the expense amount. FK to d_currency (BR-005).';
COMMENT ON COLUMN analytics.f_expense.time_id     IS 'FK to d_time. Timestamp is the single source of truth for when the expense occurred, consistent with f_transaction (BR-018).';
COMMENT ON COLUMN analytics.f_expense.category_id IS 'FK to d_expense_category. Required — every expense must be categorized (BR-020).';

-- Indexes to support the most common query patterns:
-- filtering by company, filtering by time, filtering by category

CREATE INDEX idx_f_expense_c_id
    ON analytics.f_expense (c_id);

CREATE INDEX idx_f_expense_time_id
    ON analytics.f_expense (time_id);

CREATE INDEX idx_f_expense_category_id
    ON analytics.f_expense (category_id);

COMMIT;
