-- Generated by Claude AI and reviewed for correctness by Sam Rodgers
-- Migration 005: Add f_industry
-- Description: Adds the industry aggregate fact table to the analytics schema.
--              Grain: one row per industry per day (BR-023).
--              Populated on a scheduled daily refresh — append only (BR-024).
--              Stores pre-aggregated industry metrics (BR-025, BR-026, BR-027).
-- Depends on:  001 (d_industry)
--              analytics.d_time must exist

BEGIN;

CREATE TABLE analytics.f_industry (
    industry_id          uuid            NOT NULL,
    time_id              uuid            NOT NULL,
    total_revenue        numeric(18,4)   NOT NULL,
    total_expenses       numeric(18,4)   NOT NULL,
    net_profit           numeric(18,4)   NOT NULL,
    transaction_count    integer         NOT NULL,
    avg_revenue_per_co   numeric(18,4)   NOT NULL,
    revenue_growth_rate  numeric(7,4),
    company_count        smallint        NOT NULL,

    CONSTRAINT f_industry_pkey
        PRIMARY KEY (industry_id, time_id),

    CONSTRAINT f_industry_industry_id_fkey
        FOREIGN KEY (industry_id)
        REFERENCES analytics.d_industry (industry_id),

    CONSTRAINT f_industry_time_id_fkey
        FOREIGN KEY (time_id)
        REFERENCES analytics.d_time (time_id)
);

ALTER TABLE analytics.f_industry OWNER TO alex_analytics;

COMMENT ON TABLE  analytics.f_industry                     IS 'Industry aggregate fact table. Grain: one row per industry per day (BR-023). Populated by scheduled daily refresh — never updated in place (BR-024).';
COMMENT ON COLUMN analytics.f_industry.total_revenue       IS 'Sum of f_transaction.amount across all member companies for the period (BR-025).';
COMMENT ON COLUMN analytics.f_industry.total_expenses      IS 'Sum of f_expense.amount across all member companies for the period (BR-025).';
COMMENT ON COLUMN analytics.f_industry.net_profit          IS 'total_revenue minus total_expenses for the period (BR-025).';
COMMENT ON COLUMN analytics.f_industry.transaction_count   IS 'Count of f_transaction rows across all member companies for the period (BR-025).';
COMMENT ON COLUMN analytics.f_industry.avg_revenue_per_co  IS 'total_revenue divided by company_count for the period (BR-025).';
COMMENT ON COLUMN analytics.f_industry.revenue_growth_rate IS 'Period-over-period percentage change in total_revenue. Computed at refresh time and stored directly. NULL for the first recorded period where no prior period exists (BR-026).';
COMMENT ON COLUMN analytics.f_industry.company_count       IS 'Number of distinct companies contributing to this row. Makes avg_revenue_per_co interpretable and signals membership changes between periods (BR-027).';

-- Index to support time-range queries across all industries
-- (industry_id, time_id) is already covered by the composite PK
CREATE INDEX idx_f_industry_time_id
    ON analytics.f_industry (time_id);

COMMIT;
