-- Generated by Claude AI and reviewed for correctness by Sam Rodgers
-- Migration 006: Remove apply_conversion trigger and function
-- Description: Removes trg_apply_conversion and analytics.apply_conversion()
--              because f_transaction.amount must no longer be overwritten by
--              conversion logic (BR-010, BR-011).
--              f_transaction.amount now always stores the original recorded
--              amount in its native currency. Conversion outputs live
--              entirely in f_conversion and are applied at query time.
--
--              trg_validate_conversion_currency is intentionally preserved —
--              currency matching between f_transaction and f_fx_rate remains
--              a valid business rule.
--
-- Depends on:  No dependency on prior migrations — can be applied
--              independently, but logically belongs after 001-005.
-- WARNING:     This is the only destructive migration in the set.
--              If apply_conversion has already fired on existing rows,
--              f_transaction.amount values written by the trigger will
--              remain as-is. Truncating and regenerating data after
--              this migration is strongly recommended to ensure
--              f_transaction.amount reflects native currency amounts
--              consistently (BR-010).

BEGIN;

-- Step 1: Drop the trigger first — a function that is still referenced
-- by a trigger cannot be dropped until the trigger is removed.
DROP TRIGGER IF EXISTS trg_apply_conversion
    ON analytics.f_conversion;

-- Step 2: Drop the function
DROP FUNCTION IF EXISTS analytics.apply_conversion();

COMMIT;
