-- Generated by Claude AI and reviewed for correctness by Sam Rodgers
-- Migration 007: Add raw.expense_event
-- Description: Adds the raw ingestion table for expense events, mirroring
--              the structure and conventions of raw.transaction_event.
--              Append-only enforced by the existing raw.prevent_modification
--              trigger, which is applied here on insert/update/delete.
--              No FK relationships to analytics schema (BR-003).
-- Depends on:  raw.prevent_modification() function must exist (already
--              present in the original raw schema dump).

BEGIN;

CREATE TABLE raw.expense_event (
    expense_id           uuid                     DEFAULT gen_random_uuid()
                         CONSTRAINT expense_event_expense_id_not_null    NOT NULL,
    c_id                 uuid
                         CONSTRAINT expense_event_c_id_not_null          NOT NULL,
    cncy                 varchar(3)
                         CONSTRAINT expense_event_cncy_not_null          NOT NULL,
    expense_timestamp    timestamp with time zone
                         CONSTRAINT expense_event_timestamp_not_null     NOT NULL,
    amount               numeric(18,4)
                         CONSTRAINT expense_event_amount_not_null        NOT NULL,
    category_id          uuid
                         CONSTRAINT expense_event_category_id_not_null   NOT NULL,
    ingestion_timestamp  timestamp with time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT expense_event_pkey
        PRIMARY KEY (expense_id)
);

ALTER TABLE raw.expense_event OWNER TO alex_analytics;

-- BRIN index on expense_timestamp mirrors the pattern used on
-- raw.fx_rate.fx_timestamp. Efficient for append-only time-ordered
-- data where physical row order correlates with timestamp order.
CREATE INDEX idx_expense_event_ts_brin
    ON raw.expense_event USING brin (expense_timestamp);

-- Btree index on (c_id, expense_timestamp) mirrors the pattern used on
-- raw.transaction_event for filtering by company within a time range.
CREATE INDEX idx_expense_event_c_id_timestamp
    ON raw.expense_event USING btree (c_id, expense_timestamp);

-- Enforce append-only using the existing prevent_modification trigger.
-- Fires on UPDATE and DELETE — INSERT is the only permitted operation.
CREATE TRIGGER trg_expense_event_prevent_modification
    BEFORE UPDATE OR DELETE ON raw.expense_event
    FOR EACH ROW EXECUTE FUNCTION raw.prevent_modification();

COMMIT;
