-- Migration 012: Add raw.pipeline_run table
-- Description: Persists per-run metadata for every pipeline execution so that
--              ML analysis can group transaction and quarantine rows by the
--              conditions they were generated under (noise level, row count,
--              FX source, timing).
--
--              raw.pipeline_run is keyed on batch_id, which is the same UUID
--              already stamped on raw.transaction_event.batch_id and
--              raw.quarantine_event.batch_id by the loader (since migration 008).
--              This makes pipeline_run the "header" record for each batch.
--
--              Rows are written by ml_main.py after each call to run().
--              CRON-driven runs via main.py do NOT write here — those runs will
--              have transaction rows with a batch_id that has no corresponding
--              pipeline_run record. That is expected and correct.
--
-- Depends on:  008 (raw.quarantine_event, batch_id on transaction_event)
-- Safe to run: Yes — uses CREATE TABLE IF NOT EXISTS, additive only.

BEGIN;

CREATE TABLE IF NOT EXISTS raw.pipeline_run (

    -- Primary key: the same UUID that run() stamps on every transaction and
    -- quarantine row for this batch.  Allows direct JOIN:
    --   raw.transaction_event te JOIN raw.pipeline_run pr ON te.batch_id = pr.batch_id
    batch_id            UUID                        NOT NULL,

    -- Noise configuration passed to apply_noise()
    noise_level         VARCHAR(10)                 NOT NULL
                            CHECK (noise_level IN ('low', 'medium', 'high')),

    -- Generation parameters
    n_transactions      INTEGER                     NOT NULL,
    fx_source           VARCHAR(20)                 NOT NULL,

    -- Timing
    run_timestamp       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration_seconds    NUMERIC(8, 2),

    -- Row-count outcomes from the run() return dict
    clean_count         INTEGER,
    quarantine_count    INTEGER,

    -- Free-text field for manual annotation (experiment tags, notes, etc.)
    notes               TEXT,

    CONSTRAINT pipeline_run_pkey PRIMARY KEY (batch_id)
);

-- Support queries like: "all runs at high noise in the last 7 days"
CREATE INDEX IF NOT EXISTS idx_pipeline_run_noise_level
    ON raw.pipeline_run USING btree (noise_level);

-- Support chronological listing of runs
CREATE INDEX IF NOT EXISTS idx_pipeline_run_run_timestamp
    ON raw.pipeline_run USING btree (run_timestamp DESC);

COMMENT ON TABLE raw.pipeline_run IS
    'One record per ml_main.py pipeline execution. Keyed on batch_id, which '
    'matches raw.transaction_event.batch_id and raw.quarantine_event.batch_id '
    'for the same run. Written by ml_main.py only — CRON runs via main.py do '
    'not populate this table.';

COMMENT ON COLUMN raw.pipeline_run.batch_id IS
    'UUID generated by main.run() and stamped on every raw row for this batch.';

COMMENT ON COLUMN raw.pipeline_run.noise_level IS
    'Noise scale passed to noise.apply_noise(): low=0.5x, medium=1.0x, high=2.0x.';

COMMENT ON COLUMN raw.pipeline_run.clean_count IS
    'Rows that passed normalization and were inserted into raw.transaction_event.';

COMMENT ON COLUMN raw.pipeline_run.quarantine_count IS
    'Rows that failed normalization and were inserted into raw.quarantine_event.';

COMMIT;
